name: trendychef
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  google_nav_bar: ^5.0.7
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  smooth_page_indicator: ^1.2.1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  meta: ^1.16.0
  flutter_swipe_button: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ✅ Enable localization code generation
  generate: true

  assets:
    - assets/images/riyal_logo.png
    - assets/images/trendy_logo.png
    - assets/images/google_logo.png
    - assets/images/apple_logo.png
    - assets/images/banner_1.jpg
    - assets/images/banner_2.jpg
    - assets/images/bg.png
    - assets/lottie/shopping.json
    - assets/lottie/auth.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: logofont
      fonts:
        - asset: assets/fonts/Logo-font.ttf
